### PR TITLE
Enhance: add window.gap parameter to maprange()

### PR DESCRIPTION
**Pull request by suimong**

### CODE REVIEW

**Comment by suimong** [comment]
Hi developers,

First I'm very grateful to have used your wonderful package. It helped me a lot with my data analysis project. 
During the project I have encountered some use cases that require the windows of `maprange` function to be not contiguous. For example, I have got a series of stock price at the end of each month from 2009/12/31 to 2014/12/31 and I'd like to calculate some metrics from a continuous 12 month long data, starting at every quarter, i.e. the metrics will be calculated upon: 2009/12/31-2010/12/31, 2010/03/31-2011/03/31, 2010/06/30-2011/06/30, ...
AFAIK, such behaviour is not implemented anywhere on CRAN. I decided to modify your `maprange` function because your code is very easy to understand and modify. I hope you'd find this modification useful and is suited for the purpose of `maprange` or this package in general. Thank you.

Jiaxing

**Comment by muxspace** [comment]
Hi thanks for the contribution. This is an interesting use case. It does seem like something that could be used in other situations e.g. with a step size of 1 month. I'm happy to merge it in if you can do the following:
1. rename the parameter to 'by' - that way it's consistent with seq and easier to understand;
2. add documentation that explains what the parameter is and the motivation for it.

Thanks!

**Comment by suimong** [comment]
Hi, I have made the changes to the parameter and added brief introductions to it.

**Comment by muxspace** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
